django_classified/urls.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.decorators.cache import cache_page, never_cache

from . import views, feeds, sitemap

app_name = 'django_classified'

urlpatterns = [
    url(r'^$', views.SectionListView.as_view(), name='index'),
    url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
    url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
    url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
    url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),
    url(r'^user/$', views.MyItemsView.as_view(), name='user-items'),
    url(r'^user/profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),
    url(r'^user/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^user/set-area/$', views.SetAreaView.as_view(), name='set-area'),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_classified/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from sorl.thumbnail import ImageField
from unidecode import unidecode

from . import settings as dcf_settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(_('Contact phone'), max_length=30, null=True, blank=True)
    receive_news = models.BooleanField(_('receive news'), default=True, db_index=True)

    def allow_add_item(self):
        return self.user.item_set.count() < dcf_settings.ITEM_PER_USER_LIMIT

    @staticmethod
    def get_or_create_for_user(user):
        if hasattr(user, 'profile'):
            return user.profile
        else:
            return Profile.objects.create(user=user)


@python_2_unicode_compatible
class Area(models.Model):
    slug = models.SlugField()
    title = models.CharField(_('title'), max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('area')
        verbose_name_plural = _('areas')

    @classmethod
    def get_for_request(cls, request):
        if 'area_pk' in request.session:
            try:
                return cls.objects.get(pk=request.session['area_pk'])
            except cls.DoesNotExist:
                return None
        return None

    def set_for_request(self, request):
        request.session['area_pk'] = self.pk

    @classmethod
    def delete_for_request(cls, request):
        if 'area_pk' in request.session:
            del request.session['area_pk']


@python_2_unicode_compatible
class Section(models.Model):
    title = models.CharField(_('title'), max_length=100)

    def __str__(self):
        return self.title

    @cached_property
    def count(self):
        return Item.objects \
            .filter(is_active=True) \
            .filter(group__section=self) \
            .count()

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')


@python_2_unicode_compatible
class Group(models.Model):
    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(_('title'), max_length=100)
    section = models.ForeignKey('Section', verbose_name=_('section'), on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' % (self.section.title, self.title)

    @cached_property
    def count(self):
        return self.item_set.filter(is_active=True).count()

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ['section__title', 'title', ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('group', kwargs={'pk': self.pk, 'slug': self.slug})


class ActiveManager(models.Manager):
    def get_queryset(self):
        return super(ActiveManager, self).get_queryset().filter(is_active=True)


@python_2_unicode_compatible
class Item(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, verbose_name=_('group'), on_delete=models.CASCADE)
    area = models.ForeignKey(Area, verbose_name=_('area'), on_delete=models.CASCADE, null=True, blank=True)

    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'))
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    is_active = models.BooleanField(_('active'), default=True, db_index=True)
    updated = models.DateTimeField(_('updated'), auto_now=True, db_index=True)
    posted = models.DateTimeField(_('posted'), auto_now_add=True)

    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        if not self.is_active:
            return '[%s] %s' % (_('in active'), self.title)
        else:
            return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('item', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    @cached_property
    def get_keywords(self):
        return ",".join(set(self.description.split()))

    @cached_property
    def contact_phone(self):
        return self.user.profile.phone

    @cached_property
    def image_count(self):
        return self.image_set.count()

    @cached_property
    def featured_image(self):
        return self.image_set.all().first()

    @cached_property
    def related_items(self):
        qs = Item.objects \
            .filter(is_active=True) \
            .filter(group=self.group) \
            .exclude(pk=self.pk)

        return qs[:dcf_settings.RELATED_LIMIT]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Item, self).save(*args, **kwargs)


class Image(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    file = ImageField(_('image'), upload_to='images')

django_classified/views.py
# -*- coding:utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.mail import EmailMessage, BadHeaderError
from django.forms import inlineformset_factory
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView, TemplateView
from django.views.generic.base import View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin

from . import settings as dcf_settings
from .forms import ContactForm, ItemForm, ProfileForm, SearchForm
from .models import Item, Image, Group, Section, Profile, Area


class FilteredListView(FormMixin, ListView):
    def get_form_kwargs(self):
        return {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'data': self.request.GET or None
        }

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        form = self.get_form(self.get_form_class())

        if form.is_valid():
            self.object_list = self.object_list.filter(**form.filter_by())

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class SectionListView(TemplateView):
    template_name = 'django_classified/section_list.html'

    def get_context_data(self, **kwargs):
        context = super(SectionListView, self).get_context_data(**kwargs)

        items_qs = Item.active
        area = Area.get_for_request(self.request)
        if area:
            items_qs = items_qs.filter(area=area)

        object_list = []
        # Prepare list of tuples with object/count
        for section in Section.objects.all():
            groups = [(group, items_qs.filter(group=group).count()) for group in section.group_set.all()]
            object_list.append(dict(
                section=(section, items_qs.filter(group__section=section).count()),
                groups=groups
            ))

        context['object_list'] = object_list

        return context


class SearchView(FilteredListView):
    form_class = SearchForm
    queryset = Item.active.all()
    paginate_by = 10
    template_name = 'django_classified/search.html'

    def get_initial(self):
        initials = super(SearchView, self).get_initial()
        initials['area'] = Area.get_for_request(self.request)
        return initials


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        if hasattr(self, 'get_success_message'):
            self.get_success_message(form)
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class GroupDetail(SingleObjectMixin, ListView):
    paginate_by = dcf_settings.ITEM_PER_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Group.objects.all())
        return super(GroupDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupDetail, self).get_context_data(**kwargs)
        context['group'] = self.object
        return context

    def get_queryset(self, **kwargs):
        item_qs = self.object.item_set.filter(is_active=True)
        area = Area.get_for_request(self.request)
        if area:
            return item_qs.filter(area=area)
        return item_qs


class ItemDetailView(DetailView):
    form = ContactForm()
    model = Item
    queryset = Item.active

    def get_form(self, request=None):
        if request:
            return ContactForm(request)
        return self.form

    def get_context_data(self, **kwargs):
        form = self.get_form()
        object = self.get_object()

        context = super(ItemDetailView, self).get_context_data(**kwargs)
        message = 'Hello, i would like to buy an item: {}, id: {}'.format(
            object.title,
            object.id,
        )
        form.fields['message'].initial = message
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form(request.POST)
        object = self.get_object()

        if form.is_valid():
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message'] + '\nItem url: ' + request.get_raw_uri()
            subject = form.cleaned_data['subject']
            to_email = object.user.email

            try:
                mail = EmailMessage(
                    subject=subject,
                    body=message,
                    from_email=dcf_settings.EMAIL_HOST_USER,
                    to=[to_email],
                    reply_to=[from_email],
                )
                mail.send()
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

        return redirect(object.get_absolute_url())


class ItemUpdateView(FormsetMixin, UpdateView):
    is_update_view = True
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, fields=('file',))

    def get_object(self, *args, **kwargs):
        obj = super(ItemUpdateView, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemUpdateView, self).dispatch(*args, **kwargs)


class ItemCreateView(FormsetMixin, CreateView):
    is_update_view = False
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, extra=3, fields=('file', ))

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        profile = Profile.get_or_create_for_user(self.request.user)
        if not profile.allow_add_item():
            messages.error(self.request, _('You have reached the limit!'))
            return redirect(reverse('user-items'))

        return super(ItemCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, formset):
        form.instance.user = self.request.user
        form.save()

        return super(ItemCreateView, self).form_valid(form, formset)

    def get_initial(self):
        initial = super(ItemCreateView, self).get_initial()
        initial['area'] = Area.get_for_request(self.request)
        return initial


class MyItemsView(ListView):
    template_name = 'django_classified/user_item_list.html'

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyItemsView, self).dispatch(*args, **kwargs)


class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('user-items')

    def get_queryset(self):
        qs = super(ItemDeleteView, self).get_queryset()

        if not self.request.user.is_superuser:
            qs = qs.filter(user=self.request.user)

        return qs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemDeleteView, self).dispatch(*args, **kwargs)


class ProfileView(UpdateView):
    template_name = 'django_classified/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        return Profile.get_or_create_for_user(self.request.user)

    def form_valid(self, form):
        messages.success(self.request, _('Your profile settings was updated!'))
        return super(ProfileView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileView, self).dispatch(*args, **kwargs)


class RobotsView(TemplateView):
    template_name = 'django_classified/robots.txt'
    content_type = 'text/plain'


class SetAreaView(View):
    def get(self, request):
        area_slug = request.GET.get('area_slug')
        if area_slug:
            area = get_object_or_404(Area, slug=area_slug)
            area.set_for_request(request)
        else:

django_classified/templates/django_classified/_base.html
{% spaceless %}

  {% load staticfiles i18n %}

  <!DOCTYPE HTML>
  <html lang="en">

  <head>
    <title>{% block title %}{% endblock title %} | {{ DCF.SITE_NAME }}</title>

    <meta name="description"
          content="{% block meta_description %}{{ DCF.SITE_DESCRIPTION }}{% endblock meta_description %}"/>
    <meta name="keywords" content="{% block meta_keywords %}{% endblock meta_keywords %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if GOOGLE_SITE_VERIFICATION_ID %}
      <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION_ID }}"/>
    {% endif %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    {% if FACEBOOK_APP_ID %}
      <meta property="fb:app_id" content="{{ FACEBOOK_APP_ID }}"/>
    {% endif %}
    <meta property="og:type" content="website"/>
    {% block meta_og %}{% endblock %}

    <link rel="icon" type="image/x-icon" href="{% static 'django_classified/images/favicon.ico' %}"/>

    <link href="{% static 'django_classified/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'django_classified/css/jumbotron-narrow.css' %}" rel="stylesheet"/>
    <link href="{% static 'django_classified/css/lightbox.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'django_classified/css/style.css' %}" rel="stylesheet" type="text/css"/>

    <link rel="alternate" type="application/rss+xml" href="{% url 'rss' %}">

  </head>

  <body>
  <div class="container">

    <div class="header clearfix">
      <nav>
        <ul class="nav nav-pills pull-right">
          {% if user.is_authenticated %}
            <li role="presentation" class="active"><a
                    href="{% url 'item-new' %}">{% trans "Add new" %}</a>
            </li>
          {% endif %}
          <li role="presentation"><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
          <li role="presentation"><a href="{% url 'search' %}">{% trans "Search" %}</a></li>
          {% if user.is_authenticated %}
            <li role="presentation" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-user"></span> {{ user.username }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'user-items' %}">{% trans "My items" %} ({{ user.item_set.count }})</a>
                </li>
                <li>
                  <a href="{% url 'profile' %}">{% trans "Profile" %}</a>
                </li>
                <li class="divider"></li>
                <li><a href="{% url 'logout' %}?next=/">{% trans "Logout" %}</a></li>
              </ul>
            </li>
          {% endif %}
        </ul>
      </nav>
      <h4 class="text-muted"><a href="{% url 'index' %}">{{ DCF.SITE_NAME }}</a>
        {% if area_list %}
          &nbsp;
          <small>
            <select id="area-selector">
              <option value="">{% trans 'All areas' %}</option>
              {% for area_item in area_list %}
                <option value="{{ area_item.slug }}" {% if area.pk == area_item.pk %}selected{% endif %}>
                  {{ area_item }}
                </option>
              {% endfor %}
            </select>
          </small>
        {% endif %}
      </h4>
    </div>

    {% if messages %}
      {% for message in messages %}
        <div class='row'>
          <div class="col-md-12">
            <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
              <button type="button" class="close" data-dismiss="alert">×</button>
              {{ message|safe }}
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock %}

    <footer class="footer">
      <span class="pull-left">{{ DCF.SITE_NAME }}</span>
      {% if DCF.DISPLAY_CREDITS %}
        <span class="pull-right">{% trans "Powered by" %} <a href="https://github.com/inoks/django-classified"
                                                             title="Django Classified Ads">Django Classified Ads (v{{ DCF.VERSION }})</a></span>
      {% endif %}
    </footer>

  </div>

  <script src="{% static 'django_classified/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'django_classified/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'django_classified/js/lightbox.min.js' %}"></script>

  {% block ext_scripts %}{% endblock %}

  {% if GOOGLE_ANALYTICS_PROPERTY_ID %}
    <script>
      (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

      ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
      ga('send', 'pageview');
    </script>
  {% endif %}

  <script>
    $(function () {
      $('#area-selector').on('change', function () {
        var params = {
          area_slug: this.value,
          next: window.location.href
        };
        window.location = "{% url 'set-area' %}?" + $.param(params);
      });
    });
  </script>

  <!-- generated {% now "jS F Y H:i:s" %} -->
  </body>
  </html>
{% endspaceless %}

django_classified/templates/django_classified/admin_toolbar.inc.html
{% load i18n %}

{% if user.is_superuser %}
  <div class="row">
    <div class="col-lg-12">
      <a href='{% url 'my-delete' item.pk %}' class="btn btn-danger">
        {% trans "Delete" %}
      </a>
      <a href='{% url 'item-edit' item.pk %}' class="btn btn-default">
        {% trans "Edit" %}
      </a>
    </div>
  </div>
{% endif %}

django_classified/templates/django_classified/form_pagination.inc.html
{% load i18n %}

<nav>
  <ul class="pagination">
    <li>
      <button class="btn btn-default"
              name="page"
              value="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
              type="submit"
              {% if not page_obj.has_previous %}
              disabled="disabled"
              {% endif %}>
        {% trans "Prev" %}
      </button>
    </li>

    <li>
      <button class="btn btn-default"
              name="page"
              value="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
              type="submit"
              {% if not page_obj.has_next %}
              disabled="disabled"
              {% endif %}>
        {% trans "Next" %}
      </button>
    </li>
  </ul>
</nav>

django_classified/templates/django_classified/item_confirm_delete.html
{% extends "django_classified/_base.html" %}

{% load humanize thumbnail i18n %}

{% block title %}{% trans "Delete" %} {{ object.title }}{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-lg-12">
      <form method="post">
        {% csrf_token %}
        <p>
          {% trans "Are you sure you want to delete" %}
          <a href="{{ object.get_absolute_url }}">{{ object }}</a>?
        </p>
        <input type="submit" value="{% trans "Confirm" %}" class="btn btn-danger">
      </form>
    </div>
  </div>
{% endblock %}

django_classified/templates/django_classified/item_form.html
{% extends "django_classified/_base.html" %}

{% load i18n bootstrap %}

{% block title %}{% if form.instance.pk %}{% trans "Edit" %}{% else %}{% trans "Add" %}{% endif %}
  {% trans "item" %}{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-md-12">
      <form enctype="multipart/form-data" method='post' role="form">
        {{ formset.management_form }}

        {% csrf_token %}

        {{ form|bootstrap }}

        {% for form in formset %}
          {{ form|bootstrap }}
        {% endfor %}
        <input type='submit' class="btn btn-success" value='{% trans "Save" %}'>
      </form>
    </div>
  </div>
{% endblock body %}

django_classified/templates/django_classified/item_list.html
{% extends "django_classified/_base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block body %}
  <div class="row">
    <div class="col-lg-12">
      <h4>
        <a href="{% url 'index' %}#{{ object.section.id }}">{{ object.section }}</a> > <a
              href="{{ object.get_absolute_url }}" title="{{ object.title }}">
          {{ object.title }}
        </a>
      </h4>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      {% include "django_classified/item_list.inc.html" %}
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      {% include "django_classified/list_pagination.inc.html" %}
    </div>
  </div>
{% endblock body %}

django_classified/templates/django_classified/item_list.inc.html
{% load classified %}
{% load humanize %}
{% load i18n %}
{% load thumbnail %}

{% for object in object_list %}
  {% if forloop.first %}
    <table class="table table-hover">
    <thead>
    <tr>
      <td></td>
      <td>{% trans "Price" %}</td>
    </tr>
    </thead>
    <tbody>
  {% endif %}
<tr>
  <td>
    {% if object.featured_image %}
      {% thumbnail object.featured_image.file "45x45" crop="center" as im %}
        <a href='{{ object.get_absolute_url }}' title="{{ object.title }}">
          <img
                  src='{{ im.url }}'
                  alt='{{ object.title }}'
                  title='{{ object.title }}'
                  width="{{ im.width }}"
                  height="{{ im.height }}"
                  class="img-rounded"
          />
          {% if object.image_count > 1 %}
            <span class="badge badge-notify"
                  title="{{ object.image_count|add:-1 }} {% trans 'more photos available' %}"> + {{ object.image_count|add:-1 }}</span>
          {% endif %}
        </a>
      {% endthumbnail %}
    {% endif %}
    <a href='{{ object.get_absolute_url }}' title='{{ object.title }}'>
      {{ object.title }}
    </a>
  </td>
  <td>
    {{ object.price|currency }}
  </td>
</tr>
{% if forloop.last %}
  </tbody>
  </table>
{% endif %}

{% empty %}
  <p>
    {% trans "No item here yet." %}
    <a href="{% url 'item-new' %}" class="btn btn-default">{% trans "Add one now!" %}</a>
  </p>
{% endfor %}

django_classified/templates/django_classified/list_pagination.inc.html
{% load i18n %}

<nav>
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}">{% trans "Prev" %}</a>
      </li>
    {% endif %}
    {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
      </li>
    {% endif %}
  </ul>
</nav>

django_classified/templates/django_classified/profile.html
{% extends "django_classified/_base.html" %}

{% load i18n bootstrap %}

{% block title %}{% trans "Profile" %}{% endblock title %}

{% block body %}
  <div class="row marketing">
    <div class="col-lg-12">
      <form method="post" role="form">
        {% csrf_token %}
        {{ form|bootstrap }}
        <input type="submit" value="{% trans "Update" %}" class="btn btn-default">
      </form>
    </div>
  </div>
{% endblock %}

django_classified/templates/django_classified/search.html
{% extends "django_classified/_base.html" %}

{% load i18n bootstrap %}

{% block title %}
  {% if form.q.value %}{% trans "Search results for query" %} "{{ form.q.value }}" {% else %}
    {% trans "Search" %}{% endif %}
{% endblock title %}

{% block body %}
  <div class="row">
    <div class="col-lg-6">
      <h3>{% trans "Search" %}</h3>
      <form method="get" role="form">
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-default" name="page" value="1">{% trans "Search" %}</button>
        {% if object_list|length %}
          {% include 'django_classified/form_pagination.inc.html' %}
        {% endif %}
      </form>
    </div>
  </div>
  <div>
    <hr/>
    {% if object_list|length %}
      <h4>{% blocktrans with count=page_obj.paginator.count %}Search results ({{ count }} items
        found):{% endblocktrans %}</h4>
      {% include "django_classified/item_list.inc.html" with item=object %}
    {% else %}
      <h4>{% trans "Not found" %}</h4>
    {% endif %}
  </div>
{% endblock %}